export const ADMIN_SUBMIT_REQUEST = "ADMIN_SUBMIT_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_SUBMIT_FAILURE = "ADMIN_SUBMIT_FAILURE";

export const ADMIN_LOGOUT_SUCCESS = "ADMIN_LOGOUT_SUCCESS";