export const APPLIED_FILTERS = "APPLIED_FILTERS";
export const DELIVERY_24H = "DELIVERY_24H";
export const BUSINESS_CAMEO = "BUSINESS_CAMEO";
export const SORTING_FILTER = "SORTING_FILTER";
export const PRICING_FILTER = "PRICING_FILTER";
export const RATING_FILTER = "RATING_FILTER";